dotenv: .env

dependencies:
  #<organization/repo@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  - Mudgen/diamond-3-hardhat@1.0.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
      - '@mudgen=Mudgen/diamond-3-hardhat@1.0.0'

networks:
  default: development
  kovan:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  polygon-test:
    verify: True
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'

  development:
    verify: False
  ganache-local:
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False

settings:
  gas_limit: "100000000000"

wallets:
  from_key: ${PRIVATE_KEY}
  from_key_player: ${PRIVATE_KEY_PLAYER}
  from_key_developer: ${PRIVATE_KEY_DEVELOPER}
  from_key_player_2: ${PRIVATE_KEY_PLAYER_2}